# 声明主角团
define me = Character('[P1]', color="#9031ac")
define A1 = Character('杨铃', color="#eaee0f")
define A2 = Character('白木黎', color="#f3d5ff")
define A3 = Character('A3', color="#1853d9")
define A4 = Character('姜妍', color="#acd75c")
define B1 = Character('沈岸', color="#59ffd7")
define R1 = Character('苏云雀', color="#e25940")
define R2 = Character('王逸云', color="#705050")
define R3 = Character('燕绝天', color="#d0bb32")
define C1 = Character('楚方悦', color="#0613b9")
define C2 = Character('柳韶笛', color="#ff4ba2")
define t1 = Character('宋曦', color="#dfdfdf")
define T1 = Character('宋医生', color="#dfdfdf")
define t2 = Character('夏老师', color="#334242")
define T2 = Character('夏宇安', color="#334242")
define t3 = Character('梁老师', color="#544d39")
define T3 = Character('梁清槿', color="#544d39")
